#!/bin/sh

case "$1" in
  start)
    echo "Starting bugs..."
    mkdir /root/gifs
    bugs &
    ;;
  stop)
    echo "Stopping bugs..."
    killall -9 bugs
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
